---
title: "SIOP 2021 Terrorism, Motives, LIWC"
author: "Amanda Moeller"
date: "3/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r}
library(ggplot2)
library(dplyr)
```

Upload data
```{r}
study1new <- read.csv("/Users/amandamoeller/Desktop/SIOP21/2021_latestdata.csv")
study1 <- study1new
names(study1)
```

```{r}
# rename some long variables:
study1$relig_viol <- study1$Religious.Violence..1...Religious...Violent..2...Non.Religious...Violent..3...Religious...Non.Violent..4...Non.Religious...Non.Violent.
        #  (1 = Religious & Violent, 2 = Non Religious & Violent, 3 = Religious & Non Violent, 4 = Non Religious & Non-Violent)
study1$relig <- study1$Group.religiousness..Non.religious.0..religious.1.
        # (Non-religious=0, religious=1)
study1$viol <- study1$Group.violence..0.nonviolent..1.violent.
        # (0=nonviolent, 1=violent)

# relevant vars = "Type", "relig_viol", "viol", "WC", "affiliation", "achieve", "power"
study1$Type <- as.factor(study1$Type)
study1$relig_viol <- as.factor(study1$relig_viol)
study1$viol <- as.factor(study1$viol)
study1$relig <- as.factor(study1$relig)

# type & nAff
ggplot(study1, aes(Type,affiliation))+
  geom_boxplot()

# type & nAch
ggplot(study1, aes(Type, achieve))+
  geom_boxplot()

# type & nPow
ggplot(study1, aes(Type, power))+
  geom_boxplot()

# type & word count
ggplot(study1, aes(Type, WC))+
  geom_bar(stat="identity")

# relig_viol & nAff
ggplot(study1, aes(relig_viol, affiliation))+
  geom_boxplot()

# relig_viol & nAch
ggplot(study1, aes(relig_viol, achieve))+
  geom_boxplot()

# relig_viol & nPow
ggplot(study1, aes(relig_viol, power))+
  geom_boxplot()

# viol & nAff
ggplot(study1, aes(viol, affiliation))+
  geom_boxplot()

# viol & nAch
ggplot(study1, aes(viol, achieve))+
  geom_boxplot()

# viol & nPow
ggplot(study1, aes(viol, power))+
  geom_boxplot()
```

ANOVA (do four profiles of group different?)
```{r}
oneway.test(affiliation~relig_viol, data=study1, var.equal=TRUE)
        # F = 1.9891, num df = 3, denom df = 147, p-value = 0.1181
oneway.test(achieve~relig_viol, data=study1, var.equal = TRUE)
        # F = 0.44866, num df = 3, denom df = 147, p-value = 0.7186
oneway.test(power~relig_viol, data=study1, var.equal = TRUE)
        # F = 4.8526, num df = 3, denom df = 147, p-value = 0.003005 SIG!
```

t-tests (are 2 populations different)
```{r}
# terrorist vs non-terrorist: #####################################################
t.test(affiliation~Type, data=study1)
        # t = 1.9994, df = 90.863, p-value = 0.04855
        # non-terrorist: 4.559167, terrorist: 3.115165 
        # SIG!
t.test(achieve~Type, data=study1)
        # t = -0.023757, df = 142.25, p-value = 0.9811
        # non-terrorist: 1.665500, terrorist: 1.673077
        # ns
t.test(power~Type, data=study1)
        # t = -2.2649, df = 142.72, p-value = 0.02503
        # non-terrorist: 3.60, terrorist: 5.03
        # SIG!
ggboxplot(study1, x = "Type", y = "affiliation",
          color = "Type", add = "jitter", palette="aaas") +
  stat_compare_means(method="t.test") # change colors later ig

ggboxplot(study1, x = "Type", y = "achieve",
          color = "Type", add = "jitter") +
  stat_compare_means(method="t.test") 

ggboxplot(study1, x = "Type", y = "power",
          color = "Type", add = "jitter") +
  stat_compare_means(method="t.test") 

# violent vs non-violent: #####################################################
t.test(affiliation~viol, data=study1)
        # t = 1.9658, df = 87.837, p-value = 0.05248
        # NV=4.56, V=3.12
        # SIG! (ish)
t.test(achieve~viol, data=study1)
        # t = -0.072767 df = 139.85 p-value = 0.9421
        # NV=1.668, V=1.661
        # ns
t.test(power~viol, data=study1)
        # t = 0.072767, df = 139.85, p-value = 0.9421
        # NV=3.59, V=5.02
        # SIG!
ggboxplot(study1, x = "viol", y = "affiliation",
          color = "viol", add = "jitter") +
  stat_compare_means(method="t.test") 

ggboxplot(study1, x = "viol", y = "achieve",
          color = "viol", add = "jitter") +
  stat_compare_means(method="t.test") 

ggboxplot(study1, x = "viol", y = "power",
          color = "viol", add = "jitter") +
  stat_compare_means(method="t.test") 

# relig vs non-relig: #####################################################
t.test(affiliation~relig, data=study1)
        # t = -1.1947, df = 141.61, p-value = 0.2342
        # NR= 3.28, R=4.05
        # ns
t.test(achieve~relig, data=study1)
        # t = 0.50105, df = 140.42, p-value = 0.6171
        # NR=1.76, R=1.60
        # ns
t.test(power~relig, data=study1)
        # t = 1.6078, df = 148.77, p-value = 0.11
        # NR=5.01, R=3.97
        # ns
ggboxplot(study1, x = "relig", y = "affiliation",
          color = "relig", add = "jitter") +
  stat_compare_means(method="t.test") 

ggboxplot(study1, x = "relig", y = "achieve",
          color = "relig", add = "jitter") +
  stat_compare_means(method="t.test") 

ggboxplot(study1, x = "relig", y = "power",
          color = "relig", add = "jitter") +
  stat_compare_means(method="t.test") 
```



